POST http://localhost:8090/api/collections/reservation/records
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJwYmNfMzE0MjYzNTgyMyIsImV4cCI6MTczNDQ2OTM2MiwiaWQiOiIzaWZudjhsbDhyOTkydWQiLCJyZWZyZXNoYWJsZSI6dHJ1ZSwidHlwZSI6ImF1dGgifQ.1SAbRc4bhXtnEk-92BH_PxFBWqZM5BqUnUqL2yh5gIY
Content-Type: application/json

{
  "customer_name": "John",
  "customer_phone": "0123456789",
  "customer_email": "john@doe.tld",
  "items": [
    "s4j6dg5tpd9mf80"
  ],
  "pickup": "2025-12-29 16:00:00"
}