GET http://localhost:8090/api/collections/item/records
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2xsZWN0aW9uSWQiOiJwYmNfMzE0MjYzNTgyMyIsImV4cCI6MTczMzE2MjAwNCwiaWQiOiIzaWZudjhsbDhyOTkydWQiLCJyZWZyZXNoYWJsZSI6dHJ1ZSwidHlwZSI6ImF1dGgifQ.LmJSddlHLd32n4RYpVdljQ89fIxqmBDq12mhc9OyfNs